
# conda install mamba -n base -c conda-forge

# mamba env create -f environment.yml
# mamba remove --name nvs --all -y
# mamba env update --file environment.yml --prune

name: nvs
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.15
  - pip=21.2.4
  #- conda-forge:cudatoolkit=11.6.0
  - conda-forge:cudatoolkit=11.1.1
  - pytorch-lightning==1.4.8
  - pytorch:pytorch=1.9.1
  - pytorch:torchmetrics=0.5.1
  - pytorch:torchvision=0.10.1

  - argcomplete=1.12.3
  - av=8.0.3
  - chardet=4.0.0

  - idna=3.2
  - imageio=2.9.0
  - conda-forge:matplotlib=3.6.2 #==3.4.3
  - mkl=2022.1.0
  - pandas=1.1.5
  - plotly=5.3.1

  - hydra-core=1.1.1
  - conda-forge:kornia=0.5.8
  - py=1.10.0
  - pyyaml=5.4.1
  - smmap=4.0.0
  - tabulate=0.8.9
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - timm=0.4.12
  - joblib=1.0.1

  ## Pypi dependency
  - conda-forge:trimesh=3.16.4
  - conda-forge:toml=0.10.2

  # jupyter
  - ipykernel=6.4.1
  - ipywidgets=7.6.5
  - conda-forge:jupyterlab=3.5.0
  - conda-forge:jupyterlab_widgets=3.0.3 # =1.0.2
  - conda-forge:jupyterlab_pygments=0.2.2 #=0.1.2
  - conda-forge:jupyter=1.0.0 
  - conda-forge:nest-asyncio=1.5.6 #==1.5.1
  - conda-forge:notebook=6.5.2 #==6.4.4
  - conda-forge:nbclient=0.7.0 #==0.5.4
  - conda-forge:nbconvert=6.5.3 #=7.2.5 #==6.2.0
  - conda-forge:nbformat=5.7.0 #==5.1.3

  - pip:
    - appnope==0.1.2
    - h3ds==0.1.1
    - ipython-genutils==0.2.0
    - lpips==0.1.4
    - test-tube==0.7.5
    - https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_scatter-2.0.9-cp39-cp39-linux_x86_64.whl
    
    #- kedro[pandas]==0.18.3
    #- git+https://github.com/avalonhse/pipelinex
    #- -e ../pipelinex
    #- pipelinex==0.7.6

  