scene_class_name: npbgplusplus.data.ScannetScene
scene_name: scene0000_00
train_num_samples: 2000
train_random_zoom: ~ # [ 0.5, 2.0 ]
train_random_shift: true
train_image_size: 256
data_root: ../../data/scannet_for_npbg
scene_subroot: ${datasets.data_root}
images_subroot: ${datasets.data_root}
number_of_images:
  _target_: npbgplusplus.utils.misc.number_of_files
  path: ${datasets.images_subroot}/${datasets.scene_name}/images
holdout_indices:
  _target_: npbgplusplus.utils.misc.select_indices
  margin: 10
  select: 10
  total: ${datasets.number_of_images}
val_indices:
  _target_: npbgplusplus.utils.misc.offset_indices
  indices: ${datasets.holdout_indices}
  offset: -5

cache_images: false
selection_count: 3  # during train
noise_sigma: ~
n_point: ~
image_margin: 20

train:
  - dataset_name: ${datasets.scene_name}_finetune
    dataset_class:
      _target_: npbgplusplus.data.ViewSceneWrapper
      scene_dataset:
        _target_: ${datasets.scene_class_name}
        _convert_: all
        scene_root: ${datasets.scene_subroot}/${datasets.scene_name}
        images_root: ${datasets.images_subroot}/${datasets.scene_name}/images
        pc_path: ${datasets.scene_subroot}/${datasets.scene_name}/full.ply
        num_samples: ${datasets.train_num_samples}
        random_zoom: ${datasets.train_random_zoom}
        random_shift: ${datasets.train_random_shift}
        image_size: ${datasets.train_image_size}
        exclude_indices:
          _target_: npbgplusplus.utils.misc.join_lists
          a: ${datasets.holdout_indices}
          b: ${datasets.val_indices}
        noise_sigma: ${datasets.noise_sigma}
        n_point: ${datasets.n_point}
        image_margin: ${datasets.image_margin}
      selection_count: ${datasets.selection_count}

val:
  - dataset_name: ${datasets.scene_name}_val
    dataset_class:
      _target_: npbgplusplus.data.ViewSceneWrapper
      scene_dataset:
        _target_: ${datasets.scene_class_name}
        _convert_: all
        scene_root: ${datasets.scene_subroot}/${datasets.scene_name}
        images_root: ${datasets.scene_subroot}/${datasets.scene_name}/images
        pc_path: ${datasets.scene_subroot}/${datasets.scene_name}/full.ply
        target_views_indices: ${datasets.val_indices}
        exclude_indices: ${datasets.holdout_indices}
        noise_sigma: ${datasets.noise_sigma}
        n_point: ${datasets.n_point}
        image_margin: ${datasets.image_margin}
      selection_method: ""  # we aggregate from all input views

test:
  - dataset_name: ${datasets.scene_name}_holdout
    dataset_class:
      _target_: npbgplusplus.data.ViewSceneWrapper
      scene_dataset:
        _target_: ${datasets.scene_class_name}
        _convert_: all
        scene_root: ${datasets.scene_subroot}/${datasets.scene_name}
        images_root: ${datasets.scene_subroot}/${datasets.scene_name}/images
        pc_path: ${datasets.scene_subroot}/${datasets.scene_name}/full.ply
        target_views_indices: ${datasets.holdout_indices}
        exclude_indices: ${datasets.val_indices}
        noise_sigma: ${datasets.noise_sigma}
        n_point: ${datasets.n_point}
        image_margin: ${datasets.image_margin}
      selection_method: ""  # we aggregate from all input views
